config/routes.rb
Rails.application.routes.draw do
  resources :sales
  resources :categories
  resources :products
  resources :sellers
  resources :buyers
  root to: 'page#index'
  get '/newbuyer', to: 'buyers#new'
  get '/newseller', to: 'sellers#new'
  get '/login', to: 'session#new'
  post '/login', to: 'session#create'
  get '/logout', to: 'session#destroy'
  get '/dashboard', to: 'page#admin'
  get '/forbidden', to: 'page#403'
  get '/about',  to:'page#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/seller.rb
class Seller < ApplicationRecord
  has_secure_password
  has_many :sales
  before_save {self.email = email.downcase}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 105}, uniqueness: {case_sensitivity: false}, format: {with: VALID_EMAIL_REGEX}
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :birthday, presence: true
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
  before_action :set_seller, only: [:show, :edit, :update, :destroy]
  before_action :require_logged_out, only: [:new]
  before_action :require_user, except: [:new]
  before_action :require_same_user, only: [:edit, :update, :delete, :show]



  def require_same_user
    if seller_logged_in?
    @curuser = Seller.find(session[:seller_id])
      if @curuser != Seller.find(params[:id]) && !admin_logged_in?
        redirect_to seller_url(session[:seller_id])
      end
    elsif buyer_logged_in?
      redirect_to buyer_url(session[:buyer_id])
  end
  end

  # GET /sellers
  # GET /sellers.json
  def index
    @sellers = Seller.all
  end

  # GET /sellers/1
  # GET /sellers/1.json
  def show
    @sale = Sale.all
  end

  # GET /sellers/new
  def new
    @seller = Seller.new
  end

  # GET /sellers/1/edit
  def edit
  end

  # POST /sellers
  # POST /sellers.json
  def create
    @seller = Seller.new(seller_params)

    respond_to do |format|
      if @seller.save
        format.html { redirect_to login_path, notice: 'Seller was successfully created.' }
        format.json { render :show, status: :created, location: @seller }
      else
        format.html { render :new }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sellers/1
  # PATCH/PUT /sellers/1.json
  def update
    respond_to do |format|
      if seller_logged_in?
        if @seller.update(seller_params)
          format.html { redirect_to @seller, notice: 'Welcome, new seller! Start earning!' }
          format.json { render :show, status: :ok, location: @seller }
        else
          format.html { render :edit }
          format.json { render json: @seller.errors, status: :unprocessable_entity }
        end
      elsif admin_logged_in?
        if @seller.update(seller_params)
          format.html { redirect_to dashboard_path(session[:admin_id]), notice: 'Welcome, new seller! Start earning!' }
          format.json { render :show, status: :ok, location: @seller }
        else
          format.html { render :edit }
          format.json { render json: @seller.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /sellers/1
  # DELETE /sellers/1.json
  def destroy
    @seller.destroy
    respond_to do |format|
      if admin_logged_in?
      format.html { redirect_to dashboard_path, notice: 'Seller was successfully destroyed.' }
      elsif seller_logged_in?
        format.html { redirect_to logout_path, notice: 'Seller was successfully destroyed.' }
      end
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seller
      @seller = Seller.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def seller_params
      params.require(:seller).permit(:first_name,:last_name, :email, :password,:birthday)
    end
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/views/sellers/_form.html.erb
<div class="register">
  <%= form_with(model: seller, local: true) do |form| %>
    <% if seller.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(seller.errors.count, "error") %> prohibited this seller from being saved:</h2>

        <ul>
        <% seller.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
      <p>
      <%= form.label :first_name %>
      <%= form.text_field :first_name %>
      </p>
      <p>
      <%= form.label :last_name %>
      <%= form.text_field :last_name %>
      </p>

      <p>
      <%= form.label :sex %>
      <%= form.select :sex, ['Male', 'Female']%>
      </p>
      <p>
      <%= form.label :birthday %>
      <%= form.date_field :birthday %>
      </p>

      <p>
      <%= form.label :email %>
      <%= form.text_field :email %>
      </p>
      <p>
      <%= form.label :password %>
      <%= form.password_field :password %>
      </p>
          <%= form.submit class:'button'  %>
  <% end %>
</div>

app/views/sellers/edit.html.erb
<h1>Editing Seller</h1>

<%= render 'form', seller: @seller %>

<center> <br> <br><% if !admin_logged_in? %>
<%= link_to 'Show', @seller, class:'button2' %>
<%= link_to 'Back', seller_url(@seller.id), class:'button2' %>
<%else%>
<%= link_to 'Back', dashboard_url, class:'button2' %>
<%end%>

<!--%= link_to 'Back', dashboard_path(session[:admin_id]), class: "button-back" %>

app/views/sellers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sellers</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sellers.each do |seller| %>
      <tr>
        <%if admin_logged_in? %>

        <td><%= link_to 'Edit', edit_seller_path(seller), class: 'button' %></td>
        <td><%= link_to 'Destroy', seller, class: 'button', method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>
<center><span class="button">
<%if seller_logged_in? %>
<%= link_to 'Back', seller_path(session[:seller_id])%>
<%end%>
<%if buyer_logged_in? %>
<%= link_to 'Back', buyer_path(session[:buyer_id])%>
<%end%>
</span></center>
<br>

app/views/sellers/new.html.erb
<center> <br> <br><h1> New Seller </h1>
  <%= render 'form', seller: @seller %>
<img src="/pics/gif.gif" alt="" width="120px">

app/views/sellers/show.html.erb
<center>
    <% if seller_logged_in? %>
    <img src="/pics/s.gif" width=150px id="hi">
    <%end%>
    </center>
  <div class = "form">

  <p id="notice"><%= notice %></p>
<center>

  <b>Seller: </b><%=@seller.email%> <br> <br>

  <%= link_to 'Edit Profile', edit_seller_path(@seller),class: 'navbutton' %>
  <%= link_to 'Add Products', products_path, class: 'navbutton'%>
  <%= link_to 'Add Sales', sales_path, class: 'navbutton'%>
  <%= link_to 'Delete My Profile', @seller, class: 'navbutton', method: :delete, data: { confirm: 'Are you sure you want to delete your account?' } %>
  <!--%= link_to 'Back to Home', seller_path(@seller.id) %-->
</center>  </div>
</br>
  <div class = "display">
    <div class="tables">
      <table  class="table">
      <thead >
        <tr>
          <th colspan="5"><h1>All Products</h1>
        </tr>
        <tr>
          <th>Seller</th>
          <th>Product</th>
          <th>Buyer</th>
          <th colspan="2">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @sale.each do |sale| %>
          <tr>
            <%if sale.seller_id == session[:seller_id] %>
            <td><%= Seller.find(sale.seller_id).email%></td>
            <td><%= Product.find(sale.product_id).name  %></td>
            <td>
              <% if sale.buyer_id? %>
              <%= Buyer.find(sale.buyer_id).email %>
              <%end%>
            </td>
            <td><%= link_to 'Edit', edit_sale_path(sale), class: 'tablebutton' %>
            <%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' }, class: 'tablebutton' %></td>
            <%end%>
          </tr>
        <% end %>
      </tbody>
      </table>
      </div>

      <div class="tables">
        <table  class="table">
        <thead >
          <tr>
            <th colspan="5"><h1>Available for Sale</h1>
          </tr>
          <tr>
            <th>Seller</th>
            <th>Product</th>
            <th>Buyer</th>
            <th colspan="2">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @sale.each do |sale| %>
            <tr>
              <%if sale.seller_id == session[:seller_id] && sale.buyer_id == nil %>
              <td><%= Seller.find(sale.seller_id).email%></td>
              <td><%= Product.find(sale.product_id).name  %></td>
              <td>
                <% if sale.buyer_id? %>
                <%= Buyer.find(sale.buyer_id).email %>
                <%end%>
              </td>
              <td><%= link_to 'Edit', edit_sale_path(sale), class: 'tablebutton' %>
              <%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' }, class: 'tablebutton' %></td>
              <%end%>
            </tr>
          <% end %>
        </tbody>
        </table>
        </div>
</div>
<br><br>
<br><br>
<br>
<center><img src="/pics/shop.gif" width=400px>