config/routes.rb
Rails.application.routes.draw do
  resources :sales
  resources :categories
  resources :products
  resources :sellers
  resources :buyers
  root to: 'page#index'
  get '/newbuyer', to: 'buyers#new'
  get '/newseller', to: 'sellers#new'
  get '/login', to: 'session#new'
  post '/login', to: 'session#create'
  get '/logout', to: 'session#destroy'
  get '/dashboard', to: 'page#admin'
  get '/forbidden', to: 'page#403'
  get '/about',  to:'page#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/page/403.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>error 403: forbidden</h1>
  </body>
</html>

app/views/page/about.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>	 
<br><br>   
	<center><img src="/pics/about.gif" width="300" </a>
	<center>
		<br><br>
		<div class="g">
	<div class="gallery">
    <img src="/pics/a.png" width="300" height="200"> </a>
  <div class="desc"><b>ANDII CHUNG </b><br> Mar 1998<br> BS MIS</div>
</div>
	<div class="gallery">
    <img src="/pics/p.png" width="300" height="200"> </a>
  <div class="desc"><b>PAOLO SANCHEZ</b><br> Aug 1998<br> BS MIS</div>
</div>
	<div class="gallery">
    <img src="/pics/t.png" width="300" height="200"> </a>
  <div class="desc"><b>TRIA GONZALES</b><br> Sept 1998<br> BS MIS </div>
</div>
</div>
</center>


</body>
</html>

app/views/page/admin.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <center>
    <!--h1>Admin Page</h1-->
    <br>
<div class = "display">
  <div class="tables">
    <table  class="table">
    <thead >
      <tr>
        <th colspan="3"><h1>List of buyers</h1>
      </tr>
      <tr>
        <th>Email</th>
        <th>Actions</th>
      </tr>
    </thead>
      <tbody>
          <% @buyers.each do |buyer| %>
          <td height = "30">email: <%=buyer.email%></td>
          <td><%= link_to 'Edit', edit_buyer_path(buyer), class: 'tablebutton' %>
            <%= link_to 'Destroy', buyer, method: :delete, data: { confirm: 'Are you sure?' }, class: 'tablebutton' %></td>
      </tbody>
      <% end %>
    </table>
    </div>

</br>
  <div class="tables">
  <table class="table">
  <thead >
    <tr>
      <th colspan="3"><h1>List of sellers</h1></th>
    </tr>
    <tr>
      <th>Email</th>
      <th>Actions</th>
    </tr>
  </thead>
    <tbody>
        <% @sellers.each do |seller| %>
        <td height = "30">email: <%=seller.email%></td>
        <td><%= link_to 'Edit', edit_seller_path(seller), class: 'tablebutton' %>
          <%= link_to 'Destroy', seller, method: :delete, data: { confirm: 'Are you sure?' }, class: 'tablebutton' %> </td>
    </tbody>
    <% end %>
  </table>
  </div>

  <div class="tables">
  <table  class="table">
  <thead >
    <tr>
      <th colspan="3"><h1>CRUD</h1>
    </tr>
    <tr>
      <th colspan="3">Actions</th>
    </tr>
    <tr>
      <th height = "30" width = "30"><%= link_to 'Categories', categories_path, class: 'tablebutton' %></th>
      <th><%= link_to 'Products', products_path, class: 'tablebutton'%></th>
      <th><%= link_to 'Sales', sales_path, class: 'tablebutton'%></th>
    </tr>
  </thead>

  </table>
  </div>
</div>
    </center>
  </body>
</html>

app/views/page/index.html.erb
`<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <center>
    <img src="/pics/title.png" alt="" id="honeydew" >
    <table  class="table">
    <thead >
      <tr>
        <th colspan="4"><h1>Available Products</h1></th>
      </tr>
      <tr>
        <th>Seller</th>
        <th>Product</th>
        <th>Price</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @sale.each do |sale| %>
      <tr>
        <% if !sale.buyer_id? %>
            <td><%= Seller.find(sale.seller_id).email%></td>
            <td><%= Product.find(sale.product_id).name  %></td>
            <td><%= sale.price%></td>
            <td><%= link_to 'Login to Buy', login_path, class: 'tablebutton' %>
            <!-- <td><button type="submit">Buy</button></td> -->
        <%end%>
        </tr>
      <%end%>
    </tbody>
    </table>
        </center>
<img src="/pics/foot.png" width="1250", class="main-footer" >
  </body>
</html>