config/routes.rb
Rails.application.routes.draw do
  resources :sales
  resources :categories
  resources :products
  resources :sellers
  resources :buyers
  root to: 'page#index'
  get '/newbuyer', to: 'buyers#new'
  get '/newseller', to: 'sellers#new'
  get '/login', to: 'session#new'
  post '/login', to: 'session#create'
  get '/logout', to: 'session#destroy'
  get '/dashboard', to: 'page#admin'
  get '/forbidden', to: 'page#403'
  get '/about',  to:'page#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  validates :name, presence: true, uniqueness: {case_sensitivity: false}
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
 before_action :require_admin
  before_action :set_category, only: [:show, :edit, :update, :destroy]


  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<div class="register">
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>
  <%= form.label :name %>
  <%= form.text_field :name %>
  </p>
        <%= form.submit class:'button'  %>
    </br>
    </br>
    <%= link_to 'Back', categories_path, class:'button-back' %>
<% end %>
</div>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

app/views/categories/index.html.erb
<div class="display">
<div class="tables">
<center>
  <p id="notice"><%= notice %></p>
  <table border="0">
    <thead>
      <tr>
        <th colspan="3">  <h1>Categories</h1></th>
      </tr>
    </thead>

    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <td height = "30"><%= category.name%></td>
          <td><%= link_to 'Edit', edit_category_path(category), class: 'tablebutton' %></td>
          <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }, class:'tablebutton' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <br>
  <%= link_to 'New Category', new_category_path, class: 'button' %>
  </br>
  </br>
  </br>
    <%= link_to "Back", dashboard_path(session[:admin_id]), class: 'button-back' %>
  </center>

</div>
  </div>

app/views/categories/new.html.erb
<h1>New Category</h1>
<%= render 'form', category: @category %>
<%= form.submit 'Create Category', class:'button' =%>
</br>
</br>
<%= link_to 'Back', categories_path, class:'button-back' %>

app/views/categories/show.html.erb
<center>
  <p id="notice"><%= notice %></p>
  </center>