config/routes.rb
Rails.application.routes.draw do
  resources :sales
  resources :categories
  resources :products
  resources :sellers
  resources :buyers
  root to: 'page#index'
  get '/newbuyer', to: 'buyers#new'
  get '/newseller', to: 'sellers#new'
  get '/login', to: 'session#new'
  post '/login', to: 'session#create'
  get '/logout', to: 'session#destroy'
  get '/dashboard', to: 'page#admin'
  get '/forbidden', to: 'page#403'
  get '/about',  to:'page#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navigation.html.erb
<nav class ="main-navbar">
  <div class="navbar-left">
      <img src="/pics/melon.png" alt="" width="80px">
    </div>
  <div class = "navbar-right">
    <% if buyer_logged_in? || seller_logged_in? || admin_logged_in? %>
    <%= link_to "Logout", logout_path, class: 'navbutton' %> <%if admin_logged_in? %>
    <%= link_to "Back to Home", dashboard_path(session[:admin_id]), class: 'navbutton' %>
    <%end%>
      <%if buyer_logged_in? %><%= link_to "Back to Home", buyer_path(session[:buyer_id]), class: 'navbutton'%>
      <%end%>
      <%if seller_logged_in? %><%= link_to 'Back to Home', seller_path(session[:seller_id]),class: 'navbutton'%><%end%>
    <% else %>
    <%= link_to "Home", root_path, class: 'navbutton' %>
    <%= link_to "About Us", about_path, class: 'navbutton' %>
    <%= link_to "Register as Buyer", newbuyer_url, class: 'navbutton' %>
    <%= link_to "Register as Seller", newseller_url, class: 'navbutton' %>
    <%= link_to "Login", login_path, class: 'navbutton'  %>
  <%end%>
  </div>
  </nav>

  <br>
  <div class="user">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Honeydew</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag '/pics/melon.png' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= yield %>
  </body>
</html>